config/routes.rb
Rails.application.routes.draw do
  resources :research_interests

  root 'news#index'
  get 'news_en/:id' => 'news#show'
  resources :news

end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/research_interest.rb
class ResearchInterest < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :date, :post, :TitleEn, :PostEn, :Publisher)
    end
end

app/controllers/research_interests_controller.rb
class ResearchInterestsController < ApplicationController
  before_action :set_research_interest, only: [:show, :edit, :update, :destroy]

  # GET /research_interests
  # GET /research_interests.json
  def index
    @research_interests = ResearchInterest.all
  end

  # GET /research_interests/1
  # GET /research_interests/1.json
  def show
  end

  # GET /research_interests/new
  def new
    @research_interest = ResearchInterest.new
  end

  # GET /research_interests/1/edit
  def edit
  end

  # POST /research_interests
  # POST /research_interests.json
  def create
    @research_interest = ResearchInterest.new(research_interest_params)

    respond_to do |format|
      if @research_interest.save
        format.html { redirect_to @research_interest, notice: 'Research interest was successfully created.' }
        format.json { render :show, status: :created, location: @research_interest }
      else
        format.html { render :new }
        format.json { render json: @research_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /research_interests/1
  # PATCH/PUT /research_interests/1.json
  def update
    respond_to do |format|
      if @research_interest.update(research_interest_params)
        format.html { redirect_to @research_interest, notice: 'Research interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @research_interest }
      else
        format.html { render :edit }
        format.json { render json: @research_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /research_interests/1
  # DELETE /research_interests/1.json
  def destroy
    @research_interest.destroy
    respond_to do |format|
      format.html { redirect_to research_interests_url, notice: 'Research interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_research_interest
      @research_interest = ResearchInterest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def research_interest_params
      params.require(:research_interest).permit(:research_introduciton, :research_topic, :research_topic_en, :research_details, :research_details_en, :current_projects)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/research_interests_helper.rb
module ResearchInterestsHelper
end

app/views/homepage/Thermal Science and Flow Control Lab　精微熱流控制實驗室_files/homepage.css.erb
/*字體*/

#lab_logo, #lab_name{
	font-family: Arial, sans-serif;
	font-size: 1.5em;
}

#navbar, #search_box, #search_box2{
	font-family: Verdana, Arial, sans-serif;
}

p {
	font-family: ???? ;
}

#lab_logo{
	margin-left: 1.5em;
	margin-top: 1em;
	width: 5em;
	max-width: 100px;
	display: inline;
	vertical-align: middle;
}

#lab_name{
	vertical-align: middle;
	display: inline;
	vertical-align: middle;
}

#navbar {
	direction: rtl;
	margin-top: 1em; 
	margin-right: 1em;
	text-decoration: none;	
}

input[type=search] {
	-webkit-appearance: textfield;
	-webkit-box-sizing: content-box;
	font-family: inherit;
	font-size: 100%;
}
input::-webkit-search-decoration,
input::-webkit-search-cancel-button {
	display: none;
    ---------------------------------------
    width: 15px;
    padding-left: 10px;
    color: transparent;
    cursor: pointer;
}

background: #ededed url(image/search-icon.png) no-repeat 9px center;
	border: solid 1px #ccc;
	padding:  9px 10px 9px 32px;
	width: 55px;
	-webkit-border-radius: 10em;
	-moz-border-radius: 10em;
	border-radius: 10em;

	-webkit-transition: all .5s;
	-moz-transition: all .5s;
	transition: all .5s;

input[type=research]:hover {
	background-color: #fff;
}

input[type=search]:focus {
	width: 130px;
	padding-left: 32px;
	color: #000;
	background-color: #fff;
	cursor: auto;
}

nav div ul li, form div input, #search_box{
	display: inline;
}

body{
	background:
    /* top, transparent black, faked with gradient */ 
    linear-gradient(
      rgba(70, 72, 82, 0.5), 
      rgba(70, 72, 82, 0.5)
    ),
    /* bottom, image */
    url('water_vortex2.jpg');
    background-size: cover;
	z-index: -1;
}

	

background:
    /* top, transparent black, faked with gradient */ 
    linear-gradient(
      rgba(0, 0, 0, 0.7), 
      rgba(0, 0, 0, 0.7)
    ),
    /* bottom, image */
    url('homepage_background.jpg');

#scrolling_news{
	background-color: rgba(78,164,223,0.7);
	background-size: 100%;
}

app/views/homepage/_form.html.erb
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8">
    <meta name="description" content="this is a Thermal Science and Flow Control Lab.">
    <meta name="keywords" content="Thermal, Thermal Science, Flow, Flow Control, Water Drop">
    <title>Thermal Science and Flow Control Lab　精微熱流控制實驗室</title>
    <!-- 在html文件中使用link標籤添加為這個文件量身訂做的的CSS樣式表 -->
    <link rel="stylesheet" type="text/css" href="homepage.css.erb" />
    </head>
    <body>
        <!--固定導覽列-->
        <nav id="navbar" class="fixed-nav-bar">
             <ul> 
              <li><a href="file:///C:/Users/Ming-Yi%20Wang/Documents/GitHub/bernoulli/app/views/homepage/_form.html.erb?search=#">Home</a></li>
              <li><a href="http://www.polytechnique.edu/fr/paris-saclay">News</a></li>
              <li>
                <a href="http://bernoulli.iam.ntu.edu.tw/lab.htm">Lab Members</a>
                <ul>
                    <li><a href="#">Professors</a></li>
                    <li><a href="#">Postdoctorals</a></li>
                    <li><a href="#">Doctors</a></li>
                    <li><a href="#">Masters</a></li>
                    <li><a href="#">Undergraduates</a></li>
                    <li><a href="#">Alumini</a></li>
                </ul>
              </li>
              <li><a href="http://bernoulli.iam.ntu.edu.tw/services.htm">Tech Services</a></li>
              <li><a href="http://bernoulli.iam.ntu.edu.tw/courses.htm">Courses</a></li>
              <li><a href="#">Contact Us</a></li>
              <li>
                <form method="get" action="/search" id="search">
                  <input name="q" type="text" size="40" placeholder="Search..." />
                </form>
              </li>
            </ul>
        </nav>
  
        <div id="header">
        　　 <img src="液滴icon.png" id="lab_logo">
             <p id="lab_name">Thermal Science and Flow Control Lab</p>
        </div>

        
        
       <iframe class="video" id="food_video" src="https://player.vimeo.com/video/95342512?byline=0&amp;portrait=0&amp;badge=0&amp;color=fffff0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

        <ul id="search_interests">
            <li><img id="drop_icon" src="液滴icon.png"><a href="#"></a></li>
            <li><img id="coating_icon" src="塗佈icon.png"><a href="#"></a></li>
            <li><img id="microflow_icon" src="微流icon.png"><a href="#"></a></li>
            <li><img id="heat_icon" src="熱icon.jpg"><a href="#"></a></li>
        </ul> 

        <footer id="homepage_footer">
            <p>
                <br>
                Copyright &copy; 2014 Thermal Science and Flow Control Lab, Institute of Applied Mechanics, National Taiwan University. All rights reserved.<br>
                Email:mingyiwang@ntu.edu.tw   TEL: +886-2-3366-5067   Fax:+886-2-3366-5649
            </p>
        </footer>


    </body>
</html>

app/views/homepage/homepage.css.erb
/* 字體 - 字型,大小,顏色 */
@import url(http://fonts.googleapis.com/css?family=Orbitron:500|Jura:600);
#lab_name{
	font-family:'Orbitron', Arial, sans-serif;
	font-weight: 500;
	font-size: 1.5em;
}

#navbar li{
	font-family: 'Jura', Verdana, Arial, sans-serif;
	font-weight: 600;
	font-size: 20px;
}

#search input[type="text"]{
	font-family: 'Jura', Arial,Helvetica,Sans-serif;
	font-style: bold;
	font-size: 14px;
}

p {
	font-family: 'Jura', Helvetica, Tahoma, Arial, 'Heiti' , '黑体', 'SimSun', '宋体', 'STXihei', '华文细黑', 'Microsoft YaHei', '微软雅黑', sans-serif;
}

/* 插入背景圖+背景打灰 - 要用再打開封印
     / background: , top, transparent black, faked with gradient /
    background: linear-gradient(
          rgba(70, 72, 82, 0.5), 
          rgba(70, 72, 82, 0.5)
    ),
     url(water_vortex2.jpg) top left;
   */

/*網站背景色+margin:0推到全部空間+z-index設定為最底層 */
body{
     /* bottom, image */
    margin:0;
    background: #fffff0;  
    background-size: block ;
	z-index: -1;
}


/* 實驗室logo+名稱位置 */

#lab_logo{
	width: 100px;
	display: inline;
	vertical-align: middle;
	padding: 10px;
}

#lab_name{
	display: inline;
	vertical-align: middle;
}


/* 把導覽列固定在網頁上方+靠右排成一列 */
.fixed-nav-bar{
	display: inline;
	position: fixed;
	top: 0;
	right: 0;
	width: 100%;
	height: 40px;
	background-color: #00477d;
	list-style-type: none;
	text-align: right;
	z-index: 9999;
}

/* 從直欄變橫列 */
#navbar ul li{
	display: inline;
	margin: 5px;
	position: relative;
	top: -7px;
}

/* 導覽列去掉連結預設的底線 */
#navbar ul li a{
	text-decoration: none;
	padding:2px;
}
/* 導覽列設定滑鼠點擊+目前所在頁面變色 */
#navbar a:link{	color: #fffff0;}
#navbar a:visited{ color: #fffff0;}
#navbar a:hover{ color: #7ab8cc; 
	border: solid 2px #7ab8cc;
	border-radius: 8px;}
#navbar a:focus{ color: #7ab8cc;
	border: solid 2px #7ab8cc;
	border-radius: 8px;}
#navbar a:active{ color: #7ab8cc;
	border: solid 2px #7ab8cc;
	border-radius: 8px;}

/* 導覽列設定下拉式選單 */
#navbar ul li ul {
    /* 讓第二層ul跳脫文件流以利定位 */
    position:absolute;
    /* 未點擊時隱藏下拉式選單 */
    visibility: hidden;
    /* 固定寬度 */
    width:175px;
    /* 避免出現捲軸 */
    overflow:visible;
    /* 讓ul與母階層li相同位置 */
    clear:left;
    margin-top: 30px;
    margin-right: 0;
    margin-bottom: 0;
    margin-left: -7px;
}

#navbar ul li:hover ul {
    /* 觸動第一層時，顯示第二層下拉選單 */
    visibility:visible;
    background: #00477d;
    top: 0;
    left:0;
    padding-left: 3px;
}

#navbar ul li ul{       /* 把該死的左邊差距拖回來= =，我找了一天終於找到這行程式碼了 */
	padding-left: 0px;
	text-align: left;
}


#navbar ul li:hover ul li a:hover{  /* 當滑鼠移到下拉式選單時，變色顯示停留的選項 */
	color: #7ab8cc;
	border-style: none;
	border-radius: 0px; 
}
/* 搜尋bar start */
#search {
	display: inline;
	margin-right: 20px;
}

#search input[type="text"] {
    background: url(search-white.png) no-repeat 10px 6px #fffff0;
    border: 0 none;
    color: #00477d;
    width:80px;
    padding: 6px 15px 6px 35px;
    -webkit-border-radius: 20px;
    -moz-border-radius: 20px;
    border-radius: 20px;
    text-shadow: 0 2px 2px rgba(0, 0, 0, 0.2); 
    -webkit-box-shadow: 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 3px rgba(0, 0, 0, 0.3) inset;
    -moz-box-shadow: 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 3px rgba(0, 0, 0, 0.3) inset;
    box-shadow: 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 3px rgba(0, 0, 0, 0.3) inset;
    -webkit-transition: all 0.7s ease 0s;
    -moz-transition: all 0.7s ease 0s;
    -o-transition: all 0.7s ease 0s;
    transition: all 0.7s ease 0s;
    }

#search input[type="text"]:focus {
    background: url(search-dark.png) no-repeat 10px 6px #ffffff;
    border: 0 none;
    color: #6a6f75;
    width: 200px;
    -webkit-box-shadow: 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 0 rgba(0, 0, 0, 0.9) inset;
    -moz-box-shadow: 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 0 rgba(0, 0, 0, 0.9) inset;
    box-shadow: 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 0 rgba(0, 0, 0, 0.9) inset;
    text-shadow: 0 2px 3px rgba(0, 0, 0, 0.1);
    }
/* 搜尋bar end */

#header{
	background: #00477d;
	width: 100%;
	margin-top:40px;
	margin-left: 0;
	padding-right:0; 
}

#header p{
	color:#fffff0;
}

/* 影片 */
#food_video{
	display: block;
	margin-left: auto;
	margin-right: auto;
	padding: 20px;
}

/* 研究領域icon */
#search_interests{
	text-align: center;
	margin: 10px auto;
}

#search_interests li{
	display: inline;
	list-style-type: none;
	margin: 0 30px;
}
#search_interests li img{
	width: 150px;
	vertical-align: middle;

}

footer{
	margin-bottom: -20px;
	bottom: 0;
}

footer p{
	background: #00477d;
	width: 100%;
	height: 50px;
	display: block;
	margin-left: auto;
	margin-right: auto;
	color: #fffff0;
	text-align: center;
	padding: 10px;
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bernoulli</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
 
</head>
<body>

<%= yield %>


</body>
</html>

app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-horizontal" role="form">
  <div class="form-group">
    <%= f.label :新聞日期, { :class => "col-sm-2 control-label" } %><br>
    <div class="col-sm-10">
    <%= f.datetime_select :date, { :class => "col-sm-10 form-control" } %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :發佈者, { :class => "col-sm-2 control-label" } %><br>
    <div class="col-sm-10">
    <%= f.text_field :Publisher, { :class => "col-sm-10 form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :新聞標題, { :class => "col-sm-2 control-label" } %><br>
    <div class="col-sm-10">
    <%= f.text_field :title, { :class => "col-sm-10 form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :新聞內容, { :class => "col-sm-2 control-label" } %><br>
    <div class="col-sm-10">
    <%= f.text_area :post, { :class => "col-sm-10 form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :'News Title', { :class => "col-sm-2 control-label" } %><br>
    <div class="col-sm-10">
    <%= f.text_field :TitleEn, { :class => "col-sm-10 form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :'News context', { :class => "col-sm-2 control-label" }  %><br>
    <div class="col-sm-10">
    <%= f.text_field :PostEn, { :class => "col-sm-10 form-control"} %>
    </div>
  </div>
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit '發佈', data: { confirm: '確定要發佈這篇新聞嗎?' , :class => "btn btn-default" } %>
  </div>
  </form>
<% end %>

app/views/news/edit.html.erb
<h1>編輯新聞</h1>

<%= render 'form' %>

<%= link_to 'show_研究一下還要不要放', @news %> |
<%= link_to '回主選單', news_index_path %>

app/views/news/index.html.erb
<h1>新聞列表</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>新聞標題</th>
      <th>日期</th>
      <th>新聞內容</th>
      <th>發佈者</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.date %></td>
        <td><%= news.post %></td>
        <td><%= news.Publisher %></td>
        <td><%= link_to '完整內容', news %></td>
        <td><%= link_to '編輯', edit_news_path(news) %></td>
        <td><%= link_to '刪除', news, method: :delete, data: { confirm: '確定刪除這篇新聞嗎?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '發佈新聞', new_news_path %>

app/views/news/new.html.erb
<h1>新增新聞</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @news.date %>
</p>

<% if request.path.include?('news_en') %>

<p>
  <strong>Title_English:</strong>
  <%= @news.TitleEn %>
</p>

<p>
  <strong>Post_English:</strong>
  <%= @news.PostEn %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @news.Publisher %>
</p>
<% else %>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= @news.post %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @news.Publisher %>
</p>
<% end %>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>

app/views/research_interests/_form.html.erb
<%= form_for(@research_interest) do |f| %>
  <% if @research_interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@research_interest.errors.count, "error") %> prohibited this research_interest from being saved:</h2>

      <ul>
      <% @research_interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :research_introduciton %><br>
    <%= f.text_area :research_introduciton %>
  </div>
  <div class="field">
    <%= f.label :research_topic %><br>
    <%= f.text_field :research_topic %>
  </div>
  <div class="field">
    <%= f.label :research_topic_en %><br>
    <%= f.text_field :research_topic_en %>
  </div>
  <div class="field">
    <%= f.label :research_details %><br>
    <%= f.text_area :research_details %>
  </div>
  <div class="field">
    <%= f.label :research_details_en %><br>
    <%= f.text_area :research_details_en %>
  </div>
  <div class="field">
    <%= f.label :current_projects %><br>
    <%= f.text_area :current_projects %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/research_interests/edit.html.erb
<h1>Editing research_interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @research_interest %> |
<%= link_to 'Back', research_interests_path %>

app/views/research_interests/index.html.erb
<h1>Listing research_interests</h1>

<table>
  <thead>
    <tr>
      <th>Research introduciton</th>
      <th>Research topic</th>
      <th>Research topic en</th>
      <th>Research details</th>
      <th>Research details en</th>
      <th>Current projects</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @research_interests.each do |research_interest| %>
      <tr>
        <td><%= research_interest.research_introduciton %></td>
        <td><%= research_interest.research_topic %></td>
        <td><%= research_interest.research_topic_en %></td>
        <td><%= research_interest.research_details %></td>
        <td><%= research_interest.research_details_en %></td>
        <td><%= research_interest.current_projects %></td>
        <td><%= link_to 'Show', research_interest %></td>
        <td><%= link_to 'Edit', edit_research_interest_path(research_interest) %></td>
        <td><%= link_to 'Destroy', research_interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Research interest', new_research_interest_path %>

app/views/research_interests/new.html.erb
<h1>New research_interest</h1>

<%= render 'form' %>

<%= link_to 'Back', research_interests_path %>

app/views/research_interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Research introduciton:</strong>
  <%= @research_interest.research_introduciton %>
</p>

<p>
  <strong>Research topic:</strong>
  <%= @research_interest.research_topic %>
</p>

<p>
  <strong>Research topic en:</strong>
  <%= @research_interest.research_topic_en %>
</p>

<p>
  <strong>Research details:</strong>
  <%= @research_interest.research_details %>
</p>

<p>
  <strong>Research details en:</strong>
  <%= @research_interest.research_details_en %>
</p>

<p>
  <strong>Current projects:</strong>
  <%= @research_interest.current_projects %>
</p>

<%= link_to 'Edit', edit_research_interest_path(@research_interest) %> |
<%= link_to 'Back', research_interests_path %>